name 'zabbix_server'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures zabbix_server'
long_description 'Installs/Configures zabbix_server'
version '0.10.0'

depends 'mysql2_chef_gem', '~> 1.0.2'
depends 'mysql', '~> 6.1.2' 
depends 'database', '~> 4.0.3'
