default['hadoop_server']['user'] = 'hadoop'
default['hadoop_server']['user_home'] = '/home/hadoop'
default['hadoop_server']['group'] = 'hadoop'
default['hadoop_server']['folder'] = 'hadoop-2.7.2'
default['hadoop_server']['tarball'] = 'http://a.mbbsindia.com/hadoop/common/hadoop-2.7.2/hadoop-2.7.2.tar.gz'
default['hadoop_server']['tarball_path'] = '/tmp/hadoop-2.7.2.tar.gz'
default['hadoop_server']['tarball_package'] = 'hadoop-2.7.2.tar.gz'
