default['common']['bind_utils'] = 'bind-utils'
default['jre']['package'] = 'jre-8u60-linux-x64.rpm'
default['jdk']['package'] = 'jdk-8u60-linux-x64.rpm'
default['jre']['download_header'] = 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'
default['jre']['download_url'] = 'http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jre-8u60-linux-x64.rpm'
default['jdk']['download_header'] = 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'
default['jdk']['download_url'] = 'http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.rpm'
default['zabbix_agent']['group'] = 'zabbixagent'
default['zabbix_agent']['user'] = 'zabbixagent'
default['zabbix_agent']['user_home'] = '/home/zabbixagent'
default['zabbix_agent']['tarball_url'] = 'http://sourceforge.net/projects/zabbix/files/ZABBIX%20Latest%20Stable/2.4.7/zabbix-2.4.7.tar.gz/download'
default['zabbix_agent']['tarball_name'] = 'download'
default['zabbix_agent']['zabbix_folder'] = 'zabbix-2.4.7'
default['zabbix_agent']['mysql_schema_path'] = 'database/mysql/schema.sql'
