default['dns']['bind'] = 'bind'
default['dns']['named_conf_path'] = '/etc/named.conf'
default['dns']['named_conf_local_path'] = '/etc/named/named.conf.local'
default['dns']['network_cidr'] = '172.30.0.0/24'
default['dns']['reverse_zone'] = '0.30.172'
default['dns']['zone_file_path'] = '/etc/named/zones/db.bigstream.example.com'
default['dns']['reverse_zone_file_path'] = '/etc/named/zones/db.0.30.172'
default['dns']['zones_directory'] = '/etc/named/zones'
